# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00bced52299fa2100c43d955e7bb2882738d188ff85e53bd6193c7ddbd68e56c22d6602a0af92ec91a833ee75aa7fd7785b56e2cf161a698e896ea303564fd28

test:
  secret_key_base: bb6a1398301aedeb51f6377aeec6aaee71a59f65e9cdaf2a21567e101d67a5196b53381436bf70e9152f64fcd50e8af9cdeb6259cf92ff548c49f6ad11a1c867

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
